# Generated by Django 3.0.7 on 2020-07-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200628_1035'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='_post_like_+', to='users.Profile'),
        ),
    ]
